---
- name: Copy file from Jenkins workspace to Tomcat
  hosts: all
  become: yes
  vars:
    jenkins_workspace: "/var/jenkins_home/workspace/ansible-tomcat-install-deploy/demo-app/target"
    tomcat_webapps_dir: "/opt/tomcat/webapps"
    tomcat_bin_dir: "/opt/tomcat/bin"
  tasks:
    - name: Ensure Tomcat webapps directory exists
      file:
        path: "{{ tomcat_webapps_dir }}"
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: Check if WAR file exists in Jenkins workspace
      stat:
        path: "{{ jenkins_workspace }}/demo-app.war"
      register: war_file_status

    - name: Fail if WAR file is not found in Jenkins workspace
      fail:
        msg: "WAR file not found at {{ jenkins_workspace }}/demo-app.war"
      when: not war_file_status.stat.exists

    - name: Copy WAR file from Jenkins workspace to Tomcat webapps directory
      copy:
        src: "{{ jenkins_workspace }}/demo-app.war"
        dest: "{{ tomcat_webapps_dir }}/demo-app.war"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Stop Tomcat if running
      shell: "{{ tomcat_bin_dir }}/shutdown.sh"
      ignore_errors: yes
      register: shutdown_result

    - name: Wait for Tomcat to shut down
      wait_for:
        path: "{{ tomcat_webapps_dir }}/demo-app.war"
        state: absent
        timeout: 30
      when: shutdown_result.rc == 0

    - name: Start Tomcat
      shell: "{{ tomcat_bin_dir }}/startup.sh"
      register: startup_result

    - name: Verify Tomcat startup
      wait_for:
        port: 8080
        timeout: 30
      when: startup_result.rc == 0
